project:
  type: website
  output-dir: _site
  pre-render: uvx quartofetch --config ./research/_paper_sources.yml --log-file ./research/quartofetch.log

bibliography: FellowshipRefs.bib

website:
  title: "Andrew Mitchell"
  description: "Personal website of Andrew Mitchell"
  site-url: https://drandrewmitchell.com/
  repo-url: https://github.com/MitchellAcoustics/quarto-website
  # google-analytics: "G-Y7YLFF5F90"
  open-graph: true
  favicon: favicon.png
  twitter-card: 
    creator: "@acousticsman"
    site: "@acousticsman"
    card-style: "summary_large_image"
  navbar:
    # background: dark
    # foreground: light
    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - sidebar:research
      - text: "Software"
        file: software.qmd
      - text: "Resources"
        file: resources.qmd
      - text: "Blog"
        file: blog.qmd

    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/MitchellAcoustics/quarto-website
          - text: Report a bug
            url: https://github.com/MitchellAcoustics/quarto-website/issues

  sidebar:
    - id: research
      title: "Research"
      contents:
        - text: "Open Source Papers"
          file: research/papers.qmd
        - text: "Talks"
          file: research/presentations.qmd
        - text: "List of Publications"
          file: research/list-of-pubs.qmd

format:
  html:
    theme: 
      light: flatly
      dark: superhero
    css: styles.css
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: katex
    include-in-header:
      - includes.html
    highlight-style: tango
    smooth-scroll: true

render: 
  freeze: true