project:
  type: website
  output-dir: _site

website:
  title: "Drew Dimmery"
  description: "Personal website of Drew Dimmery"
  site-url: https://ddimmery.com
  repo-url: https://github.com/ddimmery/quarto-website
  google-analytics: "G-Y7YLFF5F90"
  open-graph: true
  favicon: favicon.png
  twitter-card: 
    creator: "@drewdim"
    site: "@drewdim"
    card-style: "summary_large_image"
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: research.qmd
      - href: software.qmd
      - href: blog.qmd

format:
  html:
    theme: dimmery.scss
    mainfont: "Palatino"
    monofont: "Monaspace Argon"
    css: styles.css
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: 
      method: mathjax
      url: https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js
    include-in-header:
      - includes.html
    highlight-style: tango

execute:
  freeze: auto
