[project]
name = "quarto-website"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "bib2yaml>=1.0.0",
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "pyyaml>=6.0.2",
    "fsspec>=2024.10.0",
    "loguru>=0.7.2",
]
